🐛 .gitignore: fix sandbox.py
sad-company/sad-tetrispy pull request #6
Opened 2022-11-08 20:53 UTC by Serg-Bartosh

2022-11-08 21:09 UTC, alena-bartosh commented on .gitignore
> +/src/sandbox.py
`/src` or `src`?

2022-11-09 15:02 UTC, s373r commented on .gitignore
> +/src/sandbox.py
looks like `src` is better option

2022-11-09 15:03 UTC, s373r requested changes
please change and verify

2022-11-09 15:34 UTC, alena-bartosh approved these changes

2022-11-09 15:34 UTC, s373r approved these changes

2022-11-09 15:35 UTC, merged