🐛 Fix board.py checks
sad-company/sad-tetrispy pull request #7
Opened 2022-11-08 21:04 UTC by Serg-Bartosh

2022-11-08 21:07 UTC, alena-bartosh commented on src/board.py
> +            if point.x >= self.height or point.y >= self.weight:
Do you test it? Propose to to sleep and then think again

2022-11-08 21:07 UTC, alena-bartosh commented on src/board.py
> +        if point.x <= self.height or point.y <= self.weight:
Were also

2022-11-08 21:10 UTC, s373r requested changes

2022-11-08 21:10 UTC, s373r commented on src/board.py
> +        if point.x <= self.height or point.y <= self.weight:
we need to check < 0 condition

2022-11-08 21:10 UTC, s373r commented on src/board.py
> +            if point.x >= self.height or point.y >= self.weight:
we need to check < 0 condition

2022-11-08 21:10 UTC, s373r commented on src/board.py
> +        if point.x <= self.height or point.y <= self.weight:
+ add a blank line before

2022-11-09 07:50 UTC, alena-bartosh submitted a review, later dismissed

2022-11-09 13:32 UTC, alena-bartosh commented on src/point.py
> +               or self.y < 0
Noticed that it is not correct

2022-11-09 15:01 UTC, s373r requested changes

2022-11-09 15:01 UTC, s373r commented on src/point.py
> +               or self.y < 0
> Noticed that it is not correct

yep

2022-11-09 15:44 UTC, alena-bartosh approved these changes

2022-11-09 15:45 UTC, alena-bartosh submitted a review, later dismissed

2022-11-09 15:47 UTC, alena-bartosh commented on src/point.py
> +               or self.y <= weight \
```suggestion
        return self.x < height \
               or self.y < weight \
```

2022-11-09 15:54 UTC, s373r approved these changes

2022-11-09 15:55 UTC, alena-bartosh approved these changes

2022-11-09 15:55 UTC, merged